export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const SHOW_ERROR = 'SHOW_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';

export const CLEAN_HOME_DATA = 'CLEAN_HOME_DATA';
export const SET_HOME_SEARCH_VALUE = 'SET_HOME_SEARCH_VALUE';
export const SET_HOME_SEARCH_FILTER = 'SET_HOME_SEARCH_FILTER';

export const GET_ARTISTS = 'GET_ARTISTS';
export const SET_ARTISTS = 'SET_ARTISTS';

export const GET_ALBUMS = 'GET_ALBUMS';
export const SET_ALBUMS = 'SET_ALBUMS';

export const CLEAN_ALBUM_DATA = 'CLEAN_ALBUM_DATA';
export const GET_ALBUM_BY_ID = 'GET_ALBUM_BY_ID';
export const SET_ALBUM_DATA = 'SET_ALBUM_DATA';

export const CLEAN_ARTIST_DATA = 'CLEAN_ARTIST_DATA';
export const GET_ARTIST_BY_ID = 'GET_ARTIST_BY_ID';
export const SET_ARTIST_DATA = 'SET_ARTIST_DATA';